apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config
  namespace: production

data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_DB: "mydb"

  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"