apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: production

type: Opaque

data:
  POSTGRES_USER: bXl1c2Vy        # myuser
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==  # mypassword
  DATABASE_URL: cG9zdGdyZXNxbDovL215dXNlcjpteXBhc3N3b3JkQHBvc3RncmVzOjU0MzIvbXlkYg==