apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: production
type: Opaque

stringData:
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mypassword
  DATABASE_URL: postgresql://myuser:mypassword@postgres-service:5432/mydb