stages:
  - lint
  - build
  - push
  - deploy

variables:
  BACKEND_IMAGE: $DOCKER_USERNAME/task-backend
  FRONTEND_IMAGE: $DOCKER_USERNAME/task-frontend
  # DOCKER_TLS_CERTDIR: "/certs"
  # DOCKER_HOST: tcp://docker:2376
  # DOCKER_TLS_VERIFY: "1"
  # DOCKER_CERT_PATH: "/certs/client"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_MERGE_REQUEST_ID

# ─── LINT ───────────────────────────────────────────

lint-backend:
  stage: lint
  image: python:3.11-alpine
  script:
    - pip install flake8
    - flake8 backend/

lint-frontend:
  stage: lint
  image: node:20-alpine
  script:
    - cd frontend
    - npm install
    - npm run lint

# ─── BUILD ──────────────────────────────────────────

build-backend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n $DOCKER_USERNAME:$DOCKER_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR/backend
      --dockerfile $CI_PROJECT_DIR/backend/Dockerfile
      --destination $BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA
      --destination $BACKEND_IMAGE:latest
#  now we are using kaniko after we got VPS we change it to our personal runner!


build-frontend:
  stage: build
  image: docker:24
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: $DOCKER_TLS_CERTDIR
    DOCKER_HOST: $DOCKER_HOST
    DOCKER_TLS_VERIFY: $DOCKER_TLS_VERIFY
    DOCKER_CERT_PATH: $DOCKER_CERT_PATH
  script:
    - docker build
        -t $FRONTEND_IMAGE:$CI_COMMIT_SHORT_SHA
        -t $FRONTEND_IMAGE:latest
        ./frontend

# ─── PUSH ───────────────────────────────────────────

push-backend:
  stage: push
  image: docker:24
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push $BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $BACKEND_IMAGE:latest

push-frontend:
  stage: push
  image: docker:24
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push $FRONTEND_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $FRONTEND_IMAGE:latest

# ─── DEPLOY ─────────────────────────────────────────

deploy:
  stage: deploy
  script:
    - echo "K8s not ready yet - coming soon"